name: Get Version Name

on:
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2 
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Get versionName
        run: echo "::set-output name=versionName::$(grep -m1 versionName build.gradle | cut -d '"' -f2)"
